project_id: rosebud-machine-learning
docker_container_name: &image_name
  us-central1-docker.pkg.dev/rosebud-machine-learning/vertex/disco-diffusion:v1.2
gcp_bucket_name: rosebudai-vertexai
gcp_region: us-central1

# https://cloud.google.com/vertex-ai/docs/training/configure-compute
job_run_spec:
    - machine_spec:
        machine_type: n1-standard-4
        accelerator_type: NVIDIA_TESLA_T4
        accelerator_count: 1
      replica_count: 1
      container_spec:
        image_uri: *image_name
        command: []
        args: []

enable_web_access: True
